#!/bin/bash

#Тема: Оптимизация доступа к памяти.

# Имя временного файла для записи данных экспериментов
file_name="result.txt"

# Компиляция тестовой программы без ключей оптимизации
gcc lr2_testing_process.c -o test_o -lopenblas

# Компиляция тестовой программы с оптимизацией первого уровня
gcc lr2_testing_process.c -o test_o1 -O1 -lopenblas

# Компиляция тестовой программы с оптимизацией второго уровня
gcc lr2_testing_process.c -o test_o2 -O2 -lopenblas

# Задаем число испытаний типовых задач внутри тестовых программ
test_count=20

rm ${file_name}

# Поочередный запуск тестовых программ
./test_o  -o 0 -m "${cpu_model:21}" -c ${test_count} -f "${file_name}"
echo "____________________________________________________________________"
./test_o1 -o 1 -m "${cpu_model:21}" -c ${test_count} -f "${file_name}"
echo "____________________________________________________________________"
./test_o2 -o 2 -m "${cpu_model:21}" -c ${test_count} -f "${file_name}"
echo "____________________________________________________________________"

python3 lr2_parse_data_to_csv.py -f ${file_name} -c ${test_count}

# Удаляем исполняемые файлы
rm test_*
